### ISSUE TITLE
[pip install error] pip install returns issue in Kaggle environment

### ISSUE THREAD

**Issue by Stealeristaken** [cobanov/tasnif#5]
I was trying to install a package to try on GPU at Kaggle. When I tried to pip install it, it returned an issue that can be seen in the picture.

<img width="1052" alt="Ekran Resmi 2024-03-14 10 48 35" src="https://github.com/cobanov/tasnif/assets/109769982/9be05b42-1bc2-46f7-bef2-5d9a69ea4407">

**Comment by sinanerdinc** [comment]
i am working on it

**Comment by Stealeristaken** [comment]
thank you.

**Comment by cobanov** [comment]
https://pypi.org/project/tasnif/0.1.11/
